name: Build and Publish Docker Image
run-name: ${{ github.actor }} is building and publishing the Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/mine-crash-website:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/mine-crash-website:latest

      - name: Save Docker Image
        run: docker save -o mine-crash-website.tar ghcr.io/${{ github.repository }}/mine-crash-website:latest

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: mine-crash-website_docker_image_${{ github.run_number }}
          path: mine-crash-website.tar
